### ISSUE TITLE
Context Select: double clicking a face selects all faces

### ISSUE THREAD

**Issue by xan2622** [Stromberg90/Scripts#10]
Hi.

I am not sure this is an intended behaviour or not but I find it pretty annoying.
When I try to create face loops, sometimes ContextSelect selects all faces of the mesh. 

Reproducing steps: 
- just double click on the same face, it will select all faces.
- try to create a face loop, sometimes it works, sometimes it will select all faces.

I am using the **blender-2.81-4707f1982ddb-windows64** Daily Build.

![vMuBhAonAK](https://user-images.githubusercontent.com/1732773/66273116-52d2b580-e871-11e9-8ca6-58e7906e1919.gif)

**Comment by Stromberg90** [comment]
The double click on a element to select linked is intended.
The issue where it will do that even if you click to create a loop is not intended, although last time I looked at fixing it I couldn't find a good way.

**Comment by eobet** [comment]
Is there any chance you might add toggles so one can choose which context detections you want to have active?

I personally would also like to disable the double click to select linked, but I really like the loop selections.

(Also, shortest path selection doesn't always seem to take the shortest path, funnily enough.)

**Comment by MightyBOBcnc** [comment]
Just comment out line 109 and 110 to get rid of select linked.

**Comment by Stromberg90** [comment]
Added option in the addon preferences: https://github.com/Stromberg90/Scripts/commit/285c17a2a67b53baf0618834575def9ebe00f7f7

**Comment by MightyBOBcnc** [comment]
> The issue where it will do that even if you click to create a loop is not intended, although last time I looked at fixing it I couldn't find a good way.

Hi @Stromberg90 I took a deeper look into the ```maya_face_select``` code and I might have a possible solution to fix at least some of the unintended instances of triggering Select Linked.

Delete line 155 to 160:
```python
        if previous_active_face.index in loop_faces and not previous_active_face.index == active_face.index:
            if previous_active_face.index in relevant_neighbour_faces:
                bpy.ops.mesh.edgering_select('INVOKE_DEFAULT', ring=False)
            elif active_face.index in loop_faces:
                previous_active_face.select = True
                bpy.ops.mesh.shortest_path_select(use_face_step=True)
```

And replace it with this (it's not very pretty but seems to work):
```python
        bpy.ops.mesh.loop_multi_select('INVOKE_DEFAULT', ring=False)
        bpy.ops.mesh.select_mode('INVOKE_DEFAULT', use_extend=False, use_expand=False, type='VERT')
        bpy.ops.mesh.select_mode('INVOKE_DEFAULT', use_extend=False, use_expand=False, type='FACE')
        two_loop_faces = [f.index for f in bm.faces if f.select]

        select_face(active_face)

        if previous_active_face.index in loop_faces and not previous_active_face.index == active_face.index:
            if previous_active_face.index in relevant_neighbour_faces:
                bpy.ops.mesh.edgering_select('INVOKE_DEFAULT', ring=True)
            elif active_face.index in two_loop_faces:
                previous_active_face.select = True
                bpy.ops.mesh.shortest_path_select(use_face_step=True)
        elif previous_active_face.index in two_loop_faces and not previous_active_face.index == active_face.index: 
            if active_face.index in two_loop_faces:
                previous_active_face.select = True
                bpy.ops.mesh.shortest_path_select(use_face_step=True)
```

I think the issue is that ```bpy.ops.mesh.edgering_select``` does some sort of edge detection based on where in a face you click and that will determine the 'direction' in which it will select a loop of faces.  So if you click next to the wrong edge on the second face (```active_face```, I believe) when trying to add a loop (or add a partial loop with ```shortest_path_select```) then your code will not register 'true' anywhere on line 155-160 and will therefore act on the ```else``` at line 161 and trigger Select Linked at an undesired moment.  

What I've done is add a way to get a loop of faces in both 'directions' from a quad and an elif to check against that in case the first check against loop_faces failed.  This seems to stop unintended Select Link although you'll still sometimes not get full loops, but at least it makes selecting partial loops a breeze.  The full ```maya_face_select``` looks like this now:

```python
    def maya_face_select(self, context):
        me = context.object.data
        bm = bmesh.from_edit_mesh(me)

        if len(bm.select_history) == 0:
            return

        selected_components = [e for e in bm.edges if e.select] + [f for f in bm.faces if f.select] + [v for v in bm.verts
                                                                                                       if v.select]

        active_face = bm.select_history.active
        previous_active_face = bm.select_history[len(bm.select_history) - 2]

        select_face(active_face)

        neighbour_faces = get_neighbour_faces(bm)

        relevant_neighbour_faces = [
            e for e in neighbour_faces if not e == active_face.index]

        select_face(active_face)

        bpy.ops.mesh.edgering_select('INVOKE_DEFAULT', ring=False)
        loop_faces = [f.index for f in bm.faces if f.select]

        select_face(active_face)

        bpy.ops.mesh.loop_multi_select('INVOKE_DEFAULT', ring=False)
        bpy.ops.mesh.select_mode('INVOKE_DEFAULT', use_extend=False, use_expand=False, type='VERT')
        bpy.ops.mesh.select_mode('INVOKE_DEFAULT', use_extend=False, use_expand=False, type='FACE')
        two_loop_faces = [f.index for f in bm.faces if f.select]

        select_face(active_face)

        if previous_active_face.index in loop_faces and not previous_active_face.index == active_face.index:
            if previous_active_face.index in relevant_neighbour_faces:
                bpy.ops.mesh.edgering_select('INVOKE_DEFAULT', ring=True)
            elif active_face.index in two_loop_faces:
                previous_active_face.select = True
                bpy.ops.mesh.shortest_path_select(use_face_step=True)
        elif previous_active_face.index in two_loop_faces and not previous_active_face.index == active_face.index: 
            if active_face.index in two_loop_faces:
                previous_active_face.select = True
                bpy.ops.mesh.shortest_path_select(use_face_step=True)
        else:
            if self.addon_prefs.select_linked_on_double_click:
                bpy.ops.mesh.select_linked(delimit={'NORMAL'})

        for component in selected_components:
            component.select = True

        bm.select_history.add(active_face)
        bmesh.update_edit_mesh(me)
```

(You can actually get rid of loop_faces entirely and replace it with two_loop_faces but this will have the side effect of letting you add face loops in the 'wrong direction' off of the second face due to the aforementioned edge detection.  Unfortunately I think you'd have to write your own loop selector to bypass the edge detection on ```bpy.ops.mesh.edgering_select``` and force the correct direction of face loops.)

**Comment by Stromberg90** [comment]
@MightyBOBcnc Thanks for looking into this :)
Would be great if you could submit a pull request for this, would  be easier for me to test it out and see how it feels.
And as you mentioned, there is some kind of detection to know where on the face one clicks, which is kinda finicky.
overriding that could be a option in the future.
