### ISSUE TITLE
Context Select: error while sculpting

### ISSUE THREAD

**Issue by xan2622** [Stromberg90/Scripts#11]
Hi

I noticed an error message while sculpting. I was just using the Draw (sculpting) tool.

<img width="695" alt="ContextSelect_Sculpting" src="https://user-images.githubusercontent.com/1732773/66336517-82e78a80-e93d-11e9-9c1f-af1d0b6d6173.png">

I am currently using the **blender-2.81-54a9649e2636-windows64** Daily Build.

**Comment by xan2622** [comment]
I have just tried to sculpt and I have noticed this error :

<img width="692" alt="ContextSelect_while_sculpting" src="https://user-images.githubusercontent.com/1732773/66600229-5df55080-eba5-11e9-94b8-873e0590b62f.png">

Context Select 1.0 on blender-2.81-a856c5eccffb-windows64

**Comment by Stromberg90** [comment]
Hopefully this is fixed now.
