### ISSUE TITLE
Edge to Curve, not understanding how to get it to work

### ISSUE THREAD

**Issue by semillerimages** [Stromberg90/Scripts#12]
Hi, I have selected some edges in edit mode, run the edge to curve script and this error comes up:
What am I doing wrong?

Traceback (most recent call last):
  File "C:\Users\semil\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\edge_to_curve.py", line 108, in invoke
    self.original_object = bpy.context.selected_objects[0]
IndexError: list index out of range

location: <unknown location>:-1

**Comment by Stromberg90** [comment]
I wasn't able to reproduce this, do you get it everytime and does it happen in the latest blender version too?
