### ISSUE TITLE
Install Issues

### ISSUE THREAD

**Issue by kevinmorrison** [Stromberg90/Scripts#13]
Was wondering if anyone else has had issues installing your addons? I cannot seem to get any of them to install on any 2.8 version of Blender for some weird reason.

**Comment by semillerimages** [comment]
Did you click on the "raw" version of the script and then copy and paste it into a text editor and then save as a .py file? That's what I had to do in order to get them to install properly.

**Comment by xan2622** [comment]
That @semillerimages said.

Did you see an error when you installed the scripts?
What scripts have you tried to install, and how?

**Comment by kevinmorrison** [comment]
I figured it out, for some reason when you try and use right click and save link as on the file instead of getting the file it saves the web page and calls it the py file you thought you was downloading. I had to use the clone download option instead to get the actual scripts. Something to do with Githubs new website because it never used to be that way. Anyway, got the files and they work perfectly, thanks for your hard work on these!

**Comment by semillerimages** [comment]
> That @semillerimages said.
> 
> Did you see an error when you installed the scripts?
> What scripts have you tried to install, and how?

I had the same problem as Kevin, where I was downloading the html version. When I did the steps I mentioned above, everything was fine.

**Comment by Stromberg90** [comment]
Nice to see people helping eachother out, thanks a lot :)
