### ISSUE TITLE
indexError: list index iut of range

### ISSUE THREAD

**Issue by rabago91** [Stromberg90/Scripts#18]
Hi
I was trying to use your add on, but can't make it work:
![Addon_Edges_To_Curves_Error](https://user-images.githubusercontent.com/17786431/90289908-74fa7400-de42-11ea-8a11-506e8de834c9.png)

**Comment by MightyBOBcnc** [comment]
~Can't reproduce.  Need a list of steps for how this happens.  What are you selecting, are you in edit mode, what Blender version, etc.~

Scratch that I figured out a way to trigger it.  Looking into a fix now.

**Comment by MightyBOBcnc** [comment]
@rabago91 Try installing this version:
https://github.com/Stromberg90/Scripts/blob/Index-Out-of-Range-Fix/Blender/Edge_To_Curve.py

**Comment by MightyBOBcnc** [comment]
No response in 10 days. Merged the fix into master. Updated version of the script can be downloaded there.
https://github.com/Stromberg90/Scripts/raw/master/Blender/Edge_To_Curve.py

**Comment by rabago91** [comment]
Thank you so much!
