### ISSUE TITLE
Use hotkey for Merge Tool?

### ISSUE THREAD

**Issue by miica37** [Stromberg90/Scripts#20]
Is it possible to setup a hotkey for the Merge Tool instead of having to use Search?

I wanted to run this tool every time I press Alt+W, being a noob, I try set up the hotkey using object.merge_tool but it doesn't work, I guess it is not that simple... hope there is a way for this tool to be run by a hotkey.

Thanks for the tool btw :)

**Comment by AMYO77** [comment]
Yes it's possible that's what i did, you can search in the documentation and just bind the command to a hotkey.

**Comment by AMYO77** [comment]
Yes it's possible that's what i did, you can search in the documentation and just bind the command to a hotkey.
You can make shortcut by context in blender( ex : edit mode, object mode, outliner), 
make sure this is the only shortcut bind to alt+W, if it's not it will not work.

**Comment by miica37** [comment]
Thanks AMYO77! appreciate your help, my mistake, i think i didn't set it up properly and it works now :)
