### ISSUE TITLE
Bug with Blender 2.90.1 (resolved) / Tiny request

### ISSUE THREAD

**Issue by AMYO77** [Stromberg90/Scripts#21]
First i want to say thank you, this function is amazing, coming from maya this is a must.

i'm having this error with Blender 2.90.1 : 

Traceback (most recent call last):
  File "E:\BIDULCHOUET\Blender\B_HUMAN\Scripts\addons\MergeTool.py", line 107, in modal
    for v in self.bm.verts:
ReferenceError: BMesh data of type BMesh has been removed

location: <unknown location>:-1

This is really weird cause i don't have this error in blender 2.91 alpha or blender 2.90.

Edit : This is not coming from your code, i'm sorry, this is coming from hardops,
if i use their multi edit tool and then i use yours, it throws an error/

The ability to make it merge on release is one less click , so it's more efficient in my point view, 
that's why i think your tool is superior.

A tiny request, can right click be preserve for navigation and "Esc" be used to cancel operation ?

**Comment by AMYO77** [comment]
This is not coming from your code, i'm sorry, this is coming from hardops,
if i use their merge tool and then i use yours, it throws an error, 
but since i like yours better, i will only use yours.

The ability to make it merge on release is one less click , so it's more efficient in my point view, that's why i think your tool is superior.

**Comment by MightyBOBcnc** [comment]
It might be worth investigating this even if the cause is another add-on.  

Also I'd open a new issue for the right click request.  That could potentially be made an add-on preference.
