### ISSUE TITLE
Package Edge to Curve and Merge Tool together and add UI/menu buttons?

### ISSUE THREAD

**Issue by MightyBOBcnc** [Stromberg90/Scripts#26]
A user on the Blender Artists forum would like to merge the Edge to Curve and the Merge Tool into one add-on and add buttons in the Edit mode Edge context menu to access the tools without needing to use the Search operator.  (This is particularly relevant due to the way that Blender has changed the return results from the Search operator in recent versions; everything should really go in a menu now.  See #24 )

https://blenderartists.org/t/need-assistance-to-combine-2-scripts-in-one-single-addon/1269714

I'm happy to do the work but I'd want your go-ahead first @Stromberg90 since this represents a structural change from two add-ons to one.

**Comment by Stromberg90** [comment]
Sounds good to me, as long as I can still hotkey them I don't mind.
Although, I wonder if adding them to the UI but still keeping them separate would be good?
So it would still be two add-ons, but they both have functionality in them to add themselves to the UI.

**Comment by MightyBOBcnc** [comment]
It would need a snazzy name like "StrombergTools"

**Comment by Stromberg90** [comment]
💯  this is all a front for coming up with snazzy names 😄

**Comment by MightyBOBcnc** [comment]
That user in the Blender Artists thread never got back to me.  It seems better to leave the add-ons as stand-alone.

**Comment by Stromberg90** [comment]
Yeah, I think that's the best choice for now.
