### ISSUE TITLE
It is impossible to select 2 or more objects

### ISSUE THREAD

**Issue by katrinshtorm** [Stromberg90/Scripts#29]
Your addon Merge Tool is very useful, thanks!
But I had a very unpleasant problem because of which I cannot keep it on all the time - every time I try to select 2 or more objects in Object mode using the held down shift = Traceback error occurs (in the screenshot). Perhaps this is due to the fact that I am using the Maya Config Addon (https://gumroad.com/l/FKhQL), but I'm not sure. This is very annoying, so I have to turn off everytime your addon until I need it again...
![image_2021-01-09_11-54-58](https://user-images.githubusercontent.com/77185151/104084163-a94e5100-5277-11eb-820e-71bb7450cb25.png)
![image_2021-01-09_12-06-23](https://user-images.githubusercontent.com/77185151/104084176-b9663080-5277-11eb-8365-a6a6ace26262.png)

**Comment by MightyBOBcnc** [comment]
Try this beta build.  It adds the merge tool as an icon in the toolbar (you can right click the icon to set a hotkey).
https://github.com/Stromberg90/Scripts/files/5767669/mesh_merge_tool.zip

**Comment by KatrinSummer** [comment]
Thank you! I don't see any additional icon in the toolbar, but instrument works and along with it selection of objects. But in this version every time after I merge points it quites from that mode(i can only merge 1 point with other point, then I have to call instrument again), is it normal?
![image_2021-01-09_17-13-40](https://user-images.githubusercontent.com/77185151/104089097-8aaf8080-529e-11eb-8e8e-30d1b2b98645.png)
![image_2021-01-09_17-16-18](https://user-images.githubusercontent.com/77185151/104089098-8c794400-529e-11eb-9660-6de0341a172e.png)

**Comment by MightyBOBcnc** [comment]
![image](https://user-images.githubusercontent.com/4467749/104089143-6326cc80-523a-11eb-9f24-71aaf8885d8f.png)

**Comment by KatrinSummer** [comment]
A so that's how it is. Wow, it's awesome and it works!

**Comment by MightyBOBcnc** [comment]
Also it works for merging edges too, now.

I'm hoping that I can have this new update out of beta before the end of January
