### ISSUE TITLE
There are two folders for the Mesh-merge tool within the Blender scripts folder?

### ISSUE THREAD

**Issue by Intuos5** [Stromberg90/Scripts#34]
Inside the Blender scripts folder there exist:
- A zipped folder for the Mesh Merge Tool
- An unzipped folder for the Mesh Merge Tool

Is there any difference between the two? And could the redundant folder be removed/ renamed?
![afbeelding](https://user-images.githubusercontent.com/63149655/147464765-01acb594-fa9c-4eb8-87a8-bf4f26aa2c5a.png)

Thanks for making the tool, it is one of my favourite addons actually.

**Comment by Stromberg90** [comment]
Right now they're the same, but ideally the zip file shouldn't be in the repo and instead be automatically added into the releases.
Really glad you like the tool :)
