### ISSUE TITLE
Edge to Curve & Blender 3.1 error

### ISSUE THREAD

**Issue by Dariusz1989** [Stromberg90/Scripts#35]
Hai

I'm crashing :- (((

Python: Traceback (most recent call last):
  File "C:\Users\Master\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\Edge_To_Curve.py", line 138, in invoke
    context.object.data.fill_mode = "FULL"
AttributeError: 'Mesh' object has no attribute 'fill_mode'

location: <unknown location>:-1

**Comment by Stromberg90** [comment]
I can't reproduce this in 3.1.2, what did have selected?
