### ISSUE TITLE
Issue with former openGL in 3.6+

### ISSUE THREAD

**Issue by nurb2kea** [Stromberg90/Scripts#36]
![Screenshot 2023-07-11 at 3 52 06 pm](https://github.com/Stromberg90/Scripts/assets/57676085/5776f76d-213c-43b5-95ec-f3f7b1f893e6)

**Comment by MightyBOBcnc** [comment]
Quick test. Try this version (it will show as 1.3.1) and let me know if there are any issues.
[mesh_merge_tool.zip](https://github.com/Stromberg90/Scripts/files/12021877/mesh_merge_tool.zip)

**Comment by nurb2kea** [comment]
Yepp it's working fine now. Thank you very much for the quick fix.
I guess this will be in the next build !?

**Comment by MightyBOBcnc** [comment]
Yes this will be in the 'official' 1.3.1 for the mesh merge tool.  

@Stromberg90 Are you okay with raising the minimum supported version of Blender to 2.93?  In testing it appears to be the lowest version that supports the new changes to the `gpu` module that replaces what we were using from `bgl`.  If not, we can keep supporting all the way down to 2.80 with a few if/else statements to switch to `bgl` in older versions at appropriate places in the script, which will be a little messy but functional.

**Comment by Stromberg90** [comment]
raising the minimum supported version sounds good to me.

**Comment by MightyBOBcnc** [comment]
1.3.1: 
https://github.com/Stromberg90/Scripts/raw/master/Blender/mesh_merge_tool.zip
