### ISSUE TITLE
ContextSelect Bug: Double Clicking on the mesh (Object Mode) creates an error

### ISSUE THREAD

**Issue by xan2622** [Stromberg90/Scripts#4]
Hi. I have noticed a bug while using Context Select.
I just created a UV Sphere, entered Edit Mode, selected several edges, double-clicked on several edges to create Edge Loops. Everything worked.

But then I left Edit Mode and I went back to Object Mode, double clicked on the mesh (my UV Sphere) and I got this error message:

<img width="556" alt="Capture2" src="https://user-images.githubusercontent.com/1732773/62241090-c622fb80-b3d8-11e9-9281-feaec9c9f63f.PNG">

I have tried twice these steps, I am 70-80% sure that's what I did to produce the bug.
But after that, I have tried to reproduce this bug again and again (following the same steps) without success. :confused:

And then I noticed another strange thing : double clicking in an empty area of the viewport toggled Edit Mode / Object Mode.

**Comment by Stromberg90** [comment]
Hopefully this is fixed now.
