### ISSUE TITLE
Please, upload your add-ons to the new Blender Extensions Platform

### ISSUE THREAD

**Issue by xan2622** [Stromberg90/Scripts#40]
It would be cool to see your add-ons listed  on the [Blender Extensions Platform](https://extensions.blender.org/).

Related topics: 
https://twitter.com/Blender/status/1770485472495542716
https://code.blender.org/2022/10/blender-extensions-platform/
https://devtalk.blender.org/t/2024-01-19-extensions-project/32996
https://extensions.blender.org/policies/
https://extensions.blender.org/conditions-of-use/

**Comment by Stromberg90** [comment]
Thanks, I would very much like to, now it does say that "BE will only offer **GNU GPL** compliant software"  this repo is under the MIT license, does that mean it wouldn't be allowed on the platform without a license change?

**Comment by xan2622** [comment]
Pablo Vazquez confirmed me that the MIT license is compatible. 
He edited the https://extensions.blender.org/policies/ page with this information.

You can upload your add-ons. 👍

**Comment by gregzaal** [comment]
I see this repo is MIT, but all your Blender scripts are GPL (license text at the top of the file).

**Comment by Stromberg90** [comment]
@gregzaal it's a unorthodox way to license for sure, I would like to clean this up in the future.

@xan2622 
I just tried uploading it, it won't let me with the MIT license, values I tried is.
``` toml
license = ["MIT"]
# and
license = ["MIT License"]
```
![image](https://github.com/Stromberg90/Scripts/assets/9784913/b0a3bbc4-944f-4091-9cf2-fecb915d9027)

**Comment by xan2622** [comment]
You might want to report this issue to the devs in the _Extensions-Platform-Project-feedback_ channel : 
https://blender.chat/channel/Extensions-Platform-Project-feedback

**Comment by gregzaal** [comment]
Not sure if you're aware, but as Blender itself (and its python API) are GPL, this means all Blender add-on code (anything that imports `bpy`) must be GPL as well. It's not (legally) possible to license a Blender add-on as anything other than GPL.

You can read more about this here or do some research yourself: 

* https://www.blender.org/about/license/
* https://cgcookie.com/posts/the-gpl-and-the-legal-limits-of-blender#grayareaofaddons
* https://orangeturbine.com/posts/how-to-make-your-blender-add-on-gpl-compliant

**Comment by Stromberg90** [comment]
Thanks for filing this issue, it got sorted out and it's waiting for review now :)
