### ISSUE TITLE
Context Select Bug: It selects Edge Loops that are behind the mesh

### ISSUE THREAD

**Issue by xan2622** [Stromberg90/Scripts#5]
In Edit Mode, Viewport Shading: Solid but also in Wireframe, double click on an edge to create an Edge Loop selection, everything works fine as it should. 

But if you target next to an edge, for example, in the middle of a face, Context Select creates an Edge Loop but on the back side of the mesh.

**Comment by MightyBOBcnc** [comment]
I can't reproduce that in 2.81a or 2.82.

**Comment by Stromberg90** [comment]
I'm able to sometimes reproduce it, but only in wireframe mode with x-ray enabled.
![](https://i.imgur.com/2nTX6Jv.gif)

**Comment by MightyBOBcnc** [comment]
Hmm, that looks like it's probably a Blender problem.  Blender's selection accuracy leaves a lot to be desired.  It seems to be intentionally large.
