### ISSUE TITLE
Context Select: error after double clicking on a bezier curve

### ISSUE THREAD

**Issue by xan2622** [Stromberg90/Scripts#6]
Steps:
- Add a bezier curve (the one that comes with blender by default or with the [Flexi Draw Bezier](https://github.com/Shriinivas/blenderbezierutils) tool).

- In Object Mode, double click on the curve and you should get this error:
<img width="553" alt="ContextSelect_2" src="https://user-images.githubusercontent.com/1732773/63750063-06c54600-c8ad-11e9-862b-5256bef10e0b.png">

**Comment by xan2622** [comment]
I created this issue because the error is different than the one that I reported here: [link](https://github.com/Stromberg90/Scripts/issues/4).

**Comment by Stromberg90** [comment]
Hopefully this is fixed now.
