### ISSUE TITLE
Strange behaviour of the MergeTool addon

### ISSUE THREAD

**Issue by xan2622** [Stromberg90/Scripts#9]
Hi.

I have just tested the latest version of your MergeTool addon (https://github.com/Stromberg90/Scripts/commit/beec6d981452b72f8a938648e1a221affb81ab9a) and I noticed a strange behaviour.

Vertices do merge correctly but I can see the red line (illustrating the merge) a few pixels away (mostly above).

This makes me think that there is a bug when the user is moving a vertex onto another one.

![qk6GBM6vje](https://user-images.githubusercontent.com/1732773/66256685-bf29b800-e790-11e9-8ae8-8c6448faa396.gif)

**Comment by Stromberg90** [comment]
It seems to do with the object being transformed(moved, rotated or scaled) so that's unfortenate.
I'll need to have a look at that then.

**Comment by Stromberg90** [comment]
I'm gonna revert this version for now

**Comment by Stromberg90** [comment]
Belive I have fixed this now.
